# Generated by Django 5.2.5 on 2025-12-28 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('examen_ingreso', models.DateField(blank=True, null=True, verbose_name='Examen de Ingreso')),
                ('fecha_entrega_epp', models.DateField(blank=True, help_text='Equipos de Protección Personal', null=True, verbose_name='Fecha Entrega EPP')),
                ('fecha_entrega_dotacion', models.DateField(blank=True, null=True, verbose_name='Fecha Entrega Dotación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingreso', to='trabajadores.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'db_table': 'ingreso',
                'ordering': ['-fecha_ingreso'],
            },
        ),
    ]
