# Generated by Django 5.2.5 on 2025-12-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingreso', '0002_alter_ingreso_fecha_ingreso'),
        ('trabajadores', '0004_alter_trabajador_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingreso',
            options={'ordering': ['-anio', '-fecha_ingreso'], 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AddField(
            model_name='ingreso',
            name='anio',
            field=models.IntegerField(db_index=True, default=2025, help_text='Año del ingreso (ej: 2024, 2025)', verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='ingreso',
            unique_together={('trabajador', 'anio')},
        ),
    ]
