# Generated by Django 5.2.5 on 2025-12-28 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0003_alter_trabajador_fecha_expedicion_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrativo', models.BooleanField(default=False, help_text='Marca si el trabajador participa en proyectos administrativos', verbose_name='Administrativo')),
                ('construccion_instalaciones', models.BooleanField(default=False, help_text='Marca si el trabajador participa en construcción de instalaciones', verbose_name='Construcción de Instalaciones')),
                ('construccion_redes', models.BooleanField(default=False, help_text='Marca si el trabajador participa en construcción de redes', verbose_name='Construcción de Redes')),
                ('servicios', models.BooleanField(default=False, help_text='Marca si el trabajador participa en servicios', verbose_name='Servicios')),
                ('mantenimiento_redes', models.BooleanField(default=False, help_text='Marca si el trabajador participa en mantenimiento de redes', verbose_name='Mantenimiento de Redes')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='trabajadores.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
