# Generated by Django 5.2.5 on 2025-12-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
        ('trabajadores', '0004_alter_trabajador_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-anio'], 'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AddField(
            model_name='proyecto',
            name='anio',
            field=models.IntegerField(db_index=True, default=2025, help_text='Año del proyecto (ej: 2024, 2025)', verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='administrativo',
            field=models.BooleanField(default=False, verbose_name='Administrativo'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='construccion_instalaciones',
            field=models.BooleanField(default=False, verbose_name='Construcción de Instalaciones'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='construccion_redes',
            field=models.BooleanField(default=False, verbose_name='Construcción de Redes'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='mantenimiento_redes',
            field=models.BooleanField(default=False, verbose_name='Mantenimiento de Redes'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='servicios',
            field=models.BooleanField(default=False, verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asignados', to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='proyecto',
            unique_together={('trabajador', 'anio')},
        ),
    ]
