# Generated by Django 5.2.5 on 2025-12-28 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0003_alter_trabajador_fecha_expedicion_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes (ej: 2024-01-01 para Enero 2024)', verbose_name='Mes/Año')),
                ('municipio_ejecucion', models.CharField(choices=[('ALBAN', 'Albán'), ('ALDANA', 'Aldana'), ('ANCUYA', 'Ancuyá'), ('ARBOLEDA', 'Arboleda'), ('BARBACOAS', 'Barbacoas'), ('BELEN', 'Belén'), ('BUESACO', 'Buesaco'), ('COLON', 'Colón'), ('CONSACA', 'Consacá'), ('CONTADERO', 'Contadero'), ('CORDOBA', 'Córdoba'), ('CUASPUD', 'Cuaspúd'), ('CUMBAL', 'Cumbal'), ('CUMBITARA', 'Cumbitara'), ('CHACHAGUI', 'Chachagüí'), ('EL_CHARCO', 'El Charco'), ('EL_PENOL', 'El Peñol'), ('EL_ROSARIO', 'El Rosario'), ('EL_TABLON', 'El Tablón'), ('EL_TAMBO', 'El Tambo'), ('FRANCISCO_PIZARRO', 'Francisco Pizarro'), ('FUNES', 'Fúnes'), ('GUACHUCAL', 'Guachucal'), ('GUAITARILLA', 'Guaitarilla'), ('GUALMATN', 'Gualmatán'), ('ILES', 'Iles'), ('IMUES', 'Imués'), ('IPIALES', 'Ipiales'), ('LA_CRUZ', 'La Cruz'), ('LA_FLORIDA', 'La Florida'), ('LA_LLANADA', 'La Llanada'), ('LA_TOLA', 'La Tola'), ('LA_UNION', 'La Unión'), ('LEIVA', 'Leiva'), ('LINARES', 'Linares'), ('LOS_ANDES', 'Los Andes'), ('MAGUI_PAYAN', 'Magüí Payán'), ('MALLAMA', 'Mallama'), ('MOSQUERA', 'Mosquera'), ('NARINO', 'Nariño'), ('OLAYA_HERRERA', 'Olaya Herrera'), ('OSPINA', 'Ospina'), ('PASTO', 'Pasto'), ('POLICARPA', 'Policarpa'), ('POTOSI', 'Potosí'), ('PROVIDENCIA', 'Providencia'), ('PUERRES', 'Puerres'), ('PUPIALES', 'Pupiales'), ('RICAURTE', 'Ricaurte'), ('ROBERTO_PAYAN', 'Roberto Payán'), ('SAMANIEGO', 'Samaniego'), ('SAN_BERNARDO', 'San Bernardo'), ('SAN_LORENZO', 'San Lorenzo'), ('SAN_PABLO', 'San Pablo'), ('SAN_PEDRO_CARTAGO', 'San Pedro de Cartago'), ('SANDONA', 'Sandoná'), ('SANTA_BARBARA', 'Santa Bárbara'), ('SANTACRUZ', 'Santacruz'), ('SAPUYES', 'Sapuyes'), ('TAMINANGO', 'Taminango'), ('TANGUA', 'Tangua'), ('TUMACO', 'Tumaco'), ('TUQUERRES', 'Túquerres'), ('YACUANQUER', 'Yacuanquer')], max_length=50, verbose_name='Municipio de Ejecución')),
                ('salario_cotizacion', models.DecimalField(decimal_places=2, help_text='Salario de cotización en pesos colombianos', max_digits=12, verbose_name='Salario Cotización (PILA)')),
                ('dias_laborados', models.IntegerField(help_text='Número de días trabajados en el mes', verbose_name='Días Laborados (Mes)')),
                ('sueldo_devengado', models.DecimalField(decimal_places=2, help_text='Sueldo devengado en el mes en pesos colombianos', max_digits=12, verbose_name='Sueldo Devengado (Mes)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cronogramas', to='trabajadores.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Cronograma',
                'verbose_name_plural': 'Cronogramas',
                'db_table': 'cronograma',
                'ordering': ['-mes'],
                'unique_together': {('trabajador', 'mes')},
            },
        ),
    ]
