# Generated by Django 5.2.5 on 2025-12-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='salario_cotizacion',
            field=models.DecimalField(decimal_places=2, help_text='Salario de cotización en pesos colombianos', max_digits=15, verbose_name='Salario Cotización (PILA)'),
        ),
        migrations.AlterField(
            model_name='cronograma',
            name='sueldo_devengado',
            field=models.DecimalField(decimal_places=2, help_text='Sueldo devengado en el mes en pesos colombianos', max_digits=15, verbose_name='Sueldo Devengado (Mes)'),
        ),
    ]
