# Generated by Django 5.2.5 on 2025-12-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0002_alter_cronograma_salario_cotizacion_and_more'),
        ('trabajadores', '0004_alter_trabajador_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='anio',
            field=models.IntegerField(db_index=True, default=2025, help_text='Año del cronograma (se extrae del campo mes)', verbose_name='Año'),
        ),
        migrations.AddIndex(
            model_name='cronograma',
            index=models.Index(fields=['trabajador', 'anio'], name='cronograma_trabaja_9b72bf_idx'),
        ),
        migrations.AddIndex(
            model_name='cronograma',
            index=models.Index(fields=['anio', 'mes'], name='cronograma_anio_8a6581_idx'),
        ),
    ]
