# Generated by Django 5.2.5 on 2025-12-28 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0003_alter_trabajador_fecha_expedicion_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguridadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eps', models.CharField(help_text='Entidad Promotora de Salud', max_length=200, verbose_name='EPS')),
                ('fecha_afiliacion_eps', models.DateField(blank=True, null=True, verbose_name='Fecha Afiliación EPS')),
                ('caja_compensacion', models.CharField(blank=True, help_text='Dejar vacío o poner N/A si no aplica', max_length=200, null=True, verbose_name='Caja de Compensación')),
                ('fecha_afiliacion_caja', models.DateField(blank=True, null=True, verbose_name='Fecha Afiliación Caja')),
                ('fondo_pension', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fondo de Pensión')),
                ('fecha_afiliacion_pension', models.DateField(blank=True, null=True, verbose_name='Fecha Afiliación Pensión')),
                ('arl', models.CharField(blank=True, choices=[('POSITIVA', 'Positiva'), ('SURA', 'Sura'), ('BOLIVAR', 'Bolívar'), ('LIBERTY', 'Liberty'), ('COLMENA', 'Colmena'), ('EQUIDAD', 'Equidad'), ('AURORA', 'Aurora')], help_text='Administradora de Riesgos Laborales', max_length=50, null=True, verbose_name='ARL')),
                ('riesgo', models.CharField(blank=True, choices=[('1', 'Riesgo I'), ('2', 'Riesgo II'), ('3', 'Riesgo III'), ('4', 'Riesgo IV'), ('5', 'Riesgo V')], max_length=1, null=True, verbose_name='Nivel de Riesgo')),
                ('fecha_afiliacion_arl', models.DateField(blank=True, null=True, verbose_name='Fecha Afiliación ARL')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_social', to='trabajadores.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Seguridad Social',
                'verbose_name_plural': 'Seguridad Social',
                'db_table': 'seguridad_social',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
