# Generated by Django 5.2.5 on 2025-12-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad_social', '0001_initial'),
        ('trabajadores', '0004_alter_trabajador_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seguridadsocial',
            options={'ordering': ['-anio', '-fecha_afiliacion_eps'], 'verbose_name': 'Seguridad Social', 'verbose_name_plural': 'Seguridad Social'},
        ),
        migrations.AddField(
            model_name='seguridadsocial',
            name='anio',
            field=models.IntegerField(db_index=True, default=2025, help_text='Año del registro (ej: 2024, 2025)', verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='arl',
            field=models.CharField(blank=True, choices=[('POSITIVA', 'Positiva'), ('SURA', 'Sura'), ('BOLIVAR', 'Bolívar'), ('EQUIDAD', 'Equidad'), ('LIBERTY', 'Liberty'), ('MAPFRE', 'Mapfre'), ('COLMENA', 'Colmena'), ('AURORA', 'Aurora'), ('OTRA', 'Otra')], max_length=50, null=True, verbose_name='ARL'),
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='caja_compensacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja de Compensación'),
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='eps',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='fondo_pension',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fondo de Pensión'),
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='riesgo',
            field=models.CharField(blank=True, help_text='Nivel de riesgo (I, II, III, IV, V)', max_length=10, null=True, verbose_name='Nivel de Riesgo'),
        ),
        migrations.AlterField(
            model_name='seguridadsocial',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguridad_social_registros', to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='seguridadsocial',
            unique_together={('trabajador', 'anio')},
        ),
    ]
