# Generated by Django 5.2.5 on 2025-12-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='tipo_contrato',
            field=models.CharField(choices=[('PRESTACION_SERVICIOS', 'Prestación de Servicios'), ('TERMINO_INDEFINIDO', 'Término Indefinido'), ('TERMINO_FIJO', 'Término Fijo'), ('OBRA_LABOR', 'Obra o Labor'), ('APRENDIZAJE', 'Aprendizaje')], default='PRESTACION_SERVICIOS', max_length=50, verbose_name='Tipo de Contrato'),
        ),
    ]
