# Generated by Django 5.2.5 on 2025-12-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0003_alter_contratacion_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratacion',
            name='fecha_inicio_contrato',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Contrato'),
        ),
    ]
