# Generated by Django 5.2.5 on 2025-12-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contratacion', '0004_alter_contratacion_fecha_inicio_contrato'),
        ('trabajadores', '0004_alter_trabajador_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratacion',
            options={'ordering': ['-anio', '-fecha_inicio_contrato'], 'verbose_name': 'Contratación', 'verbose_name_plural': 'Contrataciones'},
        ),
        migrations.AddField(
            model_name='contratacion',
            name='anio',
            field=models.IntegerField(db_index=True, default=2025, help_text='Año de la contratación (ej: 2024, 2025)', verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='contratacion',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones', to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='contratacion',
            unique_together={('trabajador', 'anio')},
        ),
    ]
