# Generated by Django 5.2.5 on 2025-12-28 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateField(verbose_name='Fecha de Retiro')),
                ('fecha_liquidacion', models.DateField(blank=True, null=True, verbose_name='Fecha de Liquidación')),
                ('valor_liquidacion', models.DecimalField(blank=True, decimal_places=2, help_text='Valor en pesos colombianos', max_digits=12, null=True, verbose_name='Valor Liquidación')),
                ('fecha_examen_retiro', models.DateField(blank=True, null=True, verbose_name='Fecha Examen de Retiro')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('trabajador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retiro', to='trabajadores.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
                'db_table': 'retiro',
                'ordering': ['-fecha_retiro'],
            },
        ),
    ]
