# Generated by Django 5.2.5 on 2025-12-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retiro',
            name='fecha_retiro',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Retiro'),
        ),
    ]
