# Generated by Django 5.2.5 on 2025-12-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retiro', '0002_alter_retiro_fecha_retiro'),
        ('trabajadores', '0004_alter_trabajador_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='retiro',
            options={'ordering': ['-anio', '-fecha_retiro'], 'verbose_name': 'Retiro', 'verbose_name_plural': 'Retiros'},
        ),
        migrations.AddField(
            model_name='retiro',
            name='anio',
            field=models.IntegerField(db_index=True, default=2025, help_text='Año del retiro (ej: 2024, 2025)', verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='retiro',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiros', to='trabajadores.trabajador', verbose_name='Trabajador'),
        ),
        migrations.AlterUniqueTogether(
            name='retiro',
            unique_together={('trabajador', 'anio')},
        ),
    ]
