# Generated by Django 5.2.5 on 2025-12-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='fecha_expedicion_cedula',
            field=models.DateField(default='2000-01-01', verbose_name='Fecha de Expedición de Cédula'),
        ),
    ]
