# Generated by Django 5.2.5 on 2025-12-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0003_alter_trabajador_fecha_expedicion_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='numero',
            field=models.CharField(help_text='Número de documento de identidad', max_length=20, verbose_name='Número de Identificación'),
        ),
    ]
