# Generated by Django 5.2.5 on 2025-12-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajadores', '0004_alter_trabajador_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='anio',
            field=models.IntegerField(db_index=True, default=2025, help_text='Año al que pertenece el trabajador (ej: 2024, 2025)', verbose_name='Año'),
        ),
    ]
